<?php

/**
 * @file
 * Contains Drupal\image_slider\image_slider.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Component\Utility\Html;

/**
 * Implements hook_theme().
 */
function image_slider_theme($existing, $type, $theme, $path) {
  return [
    'image_slider' => [
      'variables' => ['data' => NULL],
      'template' => 'image_slider',
    ],
  ];
}

/**
 * Implements hook_help().
 */
function image_slider_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.image_slider':
      $text = file_get_contents(__DIR__ . '/README.md');
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . Html::escape($text) . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}
