cdn_provider: ''
navbar_position: static-top
table_hover: 0
table_striped: 0
breadcrumb_home: 1
_core:
  default_config_hash: jAmtwfSVVTtk42kIXLA-a7Jblc-HBdlo9uTbKUp4UkM
schemas:
  bootstrap: 8000
  commerce_bootstrap: 8000
  belgrade: 8000
region_wells:
  navigation: ''
  top_navigation: ''
  header: ''
  highlighted: ''
  help: ''
  content: ''
  sidebar_first: ''
  sidebar_second: ''
  footer: ''
cdn_theme: ''
cdn_cache_ttl_versions: 0
cdn_cache_ttl_themes: 0
cdn_cache_ttl_assets: 0
cdn_cache_ttl_library: 0
favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'https://dev-well-really.pantheonsite.io/themes/composer/commerce_bootstrap/favicon.ico'
  use_default: false
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: false
  node_user_picture: true
logo:
  path: 'public://MicrosoftTeams-image (2).png'
  url: ''
  use_default: false
reset_http_request_cache: ''
table: ''
